import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{questions}from'./questions';

type Ans=Record<number,string>;
const DURATION=20*60;
const LEVEL='Upper-Intermediate / Advanced';
const VIOLATION_REASON='Attempt ended because the test lost focus or fullscreen mode.';

function App(){
 const[phase,setPhase]=useState<'start'|'test'|'done'|'disqualified'>('start'),[name,setName]=useState(''),[group,setGroup]=useState(''),[ans,setAns]=useState<Ans>({}),[left,setLeft]=useState(DURATION),[reason,setReason]=useState('');
 const submit=(why='Submitted by student')=>{setReason(why);setPhase('done');document.exitFullscreen?.().catch(()=>{})};
 const disqualify=()=>{setAns({});setLeft(DURATION);setReason(VIOLATION_REASON);setPhase('disqualified')};

 useEffect(()=>{if(phase!=='test')return;const id=setInterval(()=>setLeft(x=>{if(x<=1){clearInterval(id);setTimeout(()=>submit('Time expired'),0);return 0}return x-1}),1000);return()=>clearInterval(id)},[phase]);

 useEffect(()=>{if(phase!=='test')return;let ended=false;const bad=()=>{if(ended)return;ended=true;disqualify()};const vis=()=>{if(document.hidden)bad()};const fs=()=>{if(!document.fullscreenElement)bad()};window.addEventListener('blur',bad);document.addEventListener('visibilitychange',vis);document.addEventListener('fullscreenchange',fs);return()=>{window.removeEventListener('blur',bad);document.removeEventListener('visibilitychange',vis);document.removeEventListener('fullscreenchange',fs)}},[phase]);

 useEffect(()=>{const block=(e:Event)=>phase==='test'&&e.preventDefault();document.addEventListener('copy',block);document.addEventListener('cut',block);document.addEventListener('paste',block);document.addEventListener('contextmenu',block);return()=>{document.removeEventListener('copy',block);document.removeEventListener('cut',block);document.removeEventListener('paste',block);document.removeEventListener('contextmenu',block)}},[phase]);

 const score=Math.round(questions.reduce((n,q)=>n+(ans[q.id]===q.answer?1:0),0)/questions.length*100);
 const start=async()=>{if(!name.trim())return alert('Enter your full name.');setAns({});setLeft(DURATION);setReason('');try{await document.documentElement.requestFullscreen()}catch{}setPhase('test')};
 const retake=()=>{setAns({});setLeft(DURATION);setReason('');setPhase('start')};

 if(phase==='start')return <main><section className="card hero"><div className="tag">ERC ACADEMY • GRAMMAR ASSESSMENT</div><h1>Relative Clauses Test</h1><p><b>Level:</b> {LEVEL}<br/>50 scored questions • 20 minutes • Score 0–100</p><p className="muted">Coverage: defining and non-defining relative clauses, omitted relative pronouns, prepositional relative clauses, nominal relative clauses, -ever forms, reduced relative clauses, and quantifier/useful relative phrases.</p><input placeholder="Student full name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Class / group (optional)" value={group} onChange={e=>setGroup(e.target.value)}/><div className="warning"><b>Before you begin</b><br/><br/><b>DO:</b> Stay in this test window, remain in fullscreen, answer all questions, and submit before time runs out.<br/><br/><b>DON'T:</b> Switch tabs, minimize the browser, leave fullscreen, copy/paste, or open another app/window while testing.<br/><br/>Once started, the timer cannot be paused. If the test loses focus or fullscreen mode, the attempt ends immediately, the score becomes 0/100, your answers are discarded, and you must start over. No progress is saved.<br/><br/><span className="muted">Note: a normal webpage cannot reliably prevent operating-system screenshots, so the app uses focus/fullscreen monitoring instead.</span></div><button onClick={start}>Start test</button></section></main>;

 if(phase==='disqualified')return <main><section className="card hero"><div className="tag">ATTEMPT ENDED</div><h1>0/100</h1><p><b>{name}</b>{group&&<> • {group}</>}</p><p>0 correct of 50 • {reason}</p><div className="warning"><b>Your test answers have not been saved or revealed.</b><br/>You left the test window or fullscreen mode. To continue, retake the assessment from the beginning. Your previous progress has been discarded.</div><button onClick={retake}>Retake test from the beginning</button></section></main>;

 if(phase==='done')return <main><section className="card"><div className="tag">RESULTS & FEEDBACK</div><h1>{score}/100</h1><p><b>{name}</b>{group&&<> • {group}</>}</p><p>{questions.filter(q=>ans[q.id]===q.answer).length} correct of {questions.length} • {reason}</p><div className="result">{questions.map(q=><article key={q.id} className={ans[q.id]===q.answer?'ok':'bad'}><b>{q.id}. {q.text}</b><p>Your answer: {ans[q.id]||'No answer'}<br/>Correct answer: <strong>{q.answer}</strong><br/><small>{q.feedback}</small></p></article>)}</div><p className="evidence">Take a photo/screenshot of this results page and submit it to Google Classroom as instructed by your teacher.</p></section></main>;

 return <main><header><b>{name}</b><span>{Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</span></header><section className="card"><h1>Relative Clauses</h1><p className="muted">Answer every question. Your attempt is submitted automatically at 00:00. Leaving the test window or fullscreen mode ends the attempt immediately.</p>{questions.map((q,i)=><React.Fragment key={q.id}>{(i===0||questions[i-1].part!==q.part)&&<div className="part"><h2>{q.part}</h2><p>{q.instruction}</p>{q.id===21&&<p><b>Use:</b> at which | as a result of which | of which | of whom | in which | by which</p>}</div>}<article className="q"><h3>{q.id}. {q.text}</h3>{q.options.map((o,j)=><label key={o}><input type="radio" name={'q'+q.id} checked={ans[q.id]===o} onChange={()=>setAns({...ans,[q.id]:o})}/><b>{String.fromCharCode(65+j)}.</b> {o}</label>)}</article></React.Fragment>)}<button onClick={()=>confirm('Submit your test now?')&&submit()}>Submit test</button></section></main>
}createRoot(document.getElementById('root')!).render(<App/>);