import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{questions}from'./questions';
import jsPDF from'jspdf';

type Ans=Record<number,string>;
const DURATION=20*60;
const LEVEL='Upper-Intermediate / Advanced';
const VIOLATION_REASON='Attempt ended because the test lost focus or fullscreen mode.';

function App(){
 const[phase,setPhase]=useState<'start'|'test'|'done'|'disqualified'>('start'),[name,setName]=useState(''),[group,setGroup]=useState(''),[ans,setAns]=useState<Ans>({}),[left,setLeft]=useState(DURATION),[reason,setReason]=useState(''),[section,setSection]=useState(0),[showReview,setShowReview]=useState(false),[bonus,setBonus]=useState<Record<string,string>>({});
 const submit=(why='Submitted by student')=>{setReason(why);setPhase('done');document.exitFullscreen?.().catch(()=>{})};
 const disqualify=()=>{setAns({});setLeft(DURATION);setReason(VIOLATION_REASON);setPhase('disqualified')};

 useEffect(()=>{if(phase!=='test')return;const id=setInterval(()=>setLeft(x=>{if(x<=1){clearInterval(id);setTimeout(()=>submit('Time expired'),0);return 0}return x-1}),1000);return()=>clearInterval(id)},[phase]);

 useEffect(()=>{if(phase!=='test')return;let ended=false;const bad=()=>{if(ended)return;ended=true;disqualify()};const vis=()=>{if(document.hidden)bad()};const fs=()=>{if(!document.fullscreenElement)bad()};window.addEventListener('blur',bad);document.addEventListener('visibilitychange',vis);document.addEventListener('fullscreenchange',fs);return()=>{window.removeEventListener('blur',bad);document.removeEventListener('visibilitychange',vis);document.removeEventListener('fullscreenchange',fs)}},[phase]);

 useEffect(()=>{const block=(e:Event)=>phase==='test'&&e.preventDefault();document.addEventListener('copy',block);document.addEventListener('cut',block);document.addEventListener('paste',block);document.addEventListener('contextmenu',block);return()=>{document.removeEventListener('copy',block);document.removeEventListener('cut',block);document.removeEventListener('paste',block);document.removeEventListener('contextmenu',block)}},[phase]);

 const score=Math.round(questions.reduce((n,q)=>n+(ans[q.id]===q.answer?1:0),0)/questions.length*100);
 const start=async()=>{if(!name.trim())return alert('Enter your full name.');setAns({});setLeft(DURATION);setReason('');setSection(0);try{await document.documentElement.requestFullscreen()}catch{}setPhase('test')};
 const retake=()=>{setAns({});setLeft(DURATION);setReason('');setSection(0);setPhase('start')};
 const sections=[...new Set(questions.map(q=>q.part))];
 const currentPart=sections[section];
 const currentQuestions=questions.filter(q=>q.part===currentPart);
 const answered=Object.keys(ans).length;
 const progress=Math.round(answered/questions.length*100);
 const goSection=(n:number)=>{setSection(n);window.scrollTo({top:0,behavior:'smooth'})};
 const correct=questions.filter(q=>ans[q.id]===q.answer).length;
 const downloadPDF=()=>{const pdf=new jsPDF();let y=18;pdf.setFontSize(18);pdf.text('ERC Academy - Relative Clauses Test',14,y);y+=12;pdf.setFontSize(12);pdf.text('Student: '+name,14,y);y+=7;pdf.text('Class / Group: '+(group||'N/A'),14,y);y+=7;pdf.text('Score: '+score+'/100',14,y);y+=7;pdf.text('Correct: '+correct+' of '+questions.length,14,y);y+=7;pdf.text('Status: '+reason,14,y);y+=10;pdf.setFontSize(10);pdf.text('Attach this PDF to Google Classroom as your test result.',14,y);pdf.save((name.trim().replace(/\\s+/g,'-')||'student')+'-relative-clauses-result.pdf')};

 if(phase==='start')return <main className="start-shell"><section className="card hero"><div className="brand-row"><div className="brand-mark">ERC</div><div><b>ERC Academy</b><span>English Response on Command</span></div></div><div className="tag">ERC ACADEMY • GRAMMAR ASSESSMENT</div><h1>Relative Clauses Test</h1><div className="meta-pills"><span>{LEVEL}</span><span>50 questions</span><span>20 minutes</span><span>100 points</span></div><p className="muted">Coverage: defining and non-defining relative clauses, omitted relative pronouns, prepositional relative clauses, nominal relative clauses, -ever forms, reduced relative clauses, and quantifier/useful relative phrases.</p><div className="form-grid"><label className="field"><span>Student full name</span><input autoComplete="name" placeholder="e.g. Carlos Mercado" value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Class / group <em>optional</em></span><input placeholder="e.g. Level 13" value={group} onChange={e=>setGroup(e.target.value)}/></label></div><div className="rules"><div className="rules-head"><span>!</span><div><b>Before you begin</b><small>This assessment runs in secure fullscreen mode.</small></div></div><div className="rules-grid"><div><b>Do</b><p>Stay in fullscreen, answer every question, and submit before the timer reaches zero.</p></div><div><b>Don't</b><p>Switch tabs, minimize the browser, leave fullscreen, copy/paste, or open another window.</p></div></div><p className="rule-critical">Leaving the test window ends the attempt immediately with 0/100. Progress is not saved.</p></div><button className="primary wide" onClick={start}>Start assessment <span>→</span></button></section></main>;

 if(phase==='disqualified')return <main><section className="card hero"><div className="tag">ATTEMPT ENDED</div><h1>0/100</h1><p><b>{name}</b>{group&&<> • {group}</>}</p><p>0 correct of 50 • {reason}</p><div className="warning"><b>Your test answers have not been saved or revealed.</b><br/>You left the test window or fullscreen mode. To continue, retake the assessment from the beginning. Your previous progress has been discarded.</div><button onClick={retake}>Retake test from the beginning</button></section></main>;

 if(phase==='done')return <main><section className="card"><div className="tag">RESULTS & FEEDBACK</div><h1>{score}/100</h1><p><b>{name}</b>{group&&<> • {group}</>}</p><p>{correct} correct of {questions.length} • {reason}</p><div className="result-actions"><button onClick={downloadPDF}>Download result PDF</button><button className="secondary" onClick={()=>setShowReview(v=>!v)}>{showReview?'Hide answer review':'View answer review'}</button></div><p className="evidence">Download your result PDF and attach it to Google Classroom.</p>{showReview&&<div className="result">{questions.map(q=><article key={q.id} className={ans[q.id]===q.answer?'ok':'bad'}><b>{q.id}. {q.text}</b><p>Your answer: {ans[q.id]||'No answer'}<br/>Correct answer: <strong>{q.answer}</strong><br/><small>{q.feedback}</small></p></article>)}</div>}</section></main>;

 return <main className="test-shell"><header><div className="test-identity"><span className="mini-mark">ERC</span><div><b>{name}</b><small>{group||LEVEL}</small></div></div><div className={left<=300?'timer urgent':'timer'}><small>TIME LEFT</small><b>{Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</b></div></header><div className="progress-wrap"><div className="progress-meta"><b>Test progress</b><span>{answered}/50 answered • {progress}%</span></div><div className="progress-track"><div className="progress-fill" style={{width:progress+'%'}}/></div><div className="section-dots">{sections.map((_,i)=><span key={i} className={i===section?'active':i<section?'visited':''}>{i+1}</span>)}</div></div><section className="card"><div className="section-count"><span>Section {section+1} of {sections.length}</span><span>{currentQuestions.length} questions</span></div><div className="part"><h2>{currentPart}</h2><p>{currentQuestions[0]?.instruction}</p>{currentQuestions[0]?.id===21&&<p><b>Use:</b> at which | as a result of which | of which | of whom | in which | by which</p>}</div>{currentQuestions.map(q=><article className="q" key={q.id}><h3>{q.id}. {q.text}</h3>{q.options.map((o,j)=><label key={o}><input type="radio" name={'q'+q.id} checked={ans[q.id]===o} onChange={()=>setAns({...ans,[q.id]:o})}/><b>{String.fromCharCode(65+j)}.</b> {o}</label>)}</article>)}{section===sections.length-1&&<div className="bonus"><h2>Bonus — Production Challenge</h2><p>Combine each pair into one sophisticated sentence using a relative clause. These responses are for production practice and are not included in the automatic 0–100 score.</p>{[['A','We hired six new developers. Four of them specialize in mobile development.'],['B','The database crashed at 3:00 p.m. We had processed approximately 80% of the orders by then.'],['C','The company introduced a new authentication system. Because of this, unauthorized access decreased significantly.'],['D','You may choose any programming language. It must satisfy the technical requirements.'],['E','The engineers are currently testing the application. They discovered the original security vulnerability.']].map(([k,t])=><div className="bonus-q" key={k}><b>{k}. {t}</b><textarea value={bonus[k]||''} onChange={e=>setBonus({...bonus,[k]:e.target.value})} placeholder="Write your combined sentence here..." /></div>)}</div>}<div className="nav-buttons">{section>0&&<button className="secondary" onClick={()=>goSection(section-1)}>← Previous section</button>}{section<sections.length-1?<button onClick={()=>goSection(section+1)}>Next section →</button>:<button onClick={()=>confirm('Submit your test now?')&&submit()}>Submit test</button>}</div></section></main>
}createRoot(document.getElementById('root')!).render(<App/>);