import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{questions}from'./questions';

type Ans=Record<number,string>;
const DURATION=20*60;
function App(){
 const[phase,setPhase]=useState<'start'|'test'|'done'>('start'),[name,setName]=useState(''),[group,setGroup]=useState(''),[ans,setAns]=useState<Ans>({}),[left,setLeft]=useState(DURATION),[reason,setReason]=useState(''),[violations,setViolations]=useState(0);
 const submit=(why='Submitted by student')=>{setReason(why);setPhase('done');document.exitFullscreen?.().catch(()=>{})};
 useEffect(()=>{if(phase!=='test')return;const id=setInterval(()=>setLeft(x=>{if(x<=1){clearInterval(id);setTimeout(()=>submit('Time expired'),0);return 0}return x-1}),1000);return()=>clearInterval(id)},[phase]);
 useEffect(()=>{if(phase!=='test')return;const bad=()=>{setViolations(v=>v+1);submit('Attempt ended because the test lost focus or fullscreen mode.')};const vis=()=>{if(document.hidden)bad()};const fs=()=>{if(!document.fullscreenElement)bad()};window.addEventListener('blur',bad);document.addEventListener('visibilitychange',vis);document.addEventListener('fullscreenchange',fs);return()=>{window.removeEventListener('blur',bad);document.removeEventListener('visibilitychange',vis);document.removeEventListener('fullscreenchange',fs)}},[phase]);
 useEffect(()=>{const block=(e:Event)=>phase==='test'&&e.preventDefault();document.addEventListener('copy',block);document.addEventListener('cut',block);document.addEventListener('paste',block);document.addEventListener('contextmenu',block);return()=>{document.removeEventListener('copy',block);document.removeEventListener('cut',block);document.removeEventListener('paste',block);document.removeEventListener('contextmenu',block)}},[phase]);
 const score=Math.round(questions.reduce((n,q)=>n+(ans[q.id]===q.answer?1:0),0)/questions.length*100);
 const start=async()=>{if(!name.trim())return alert('Enter your full name.');try{await document.documentElement.requestFullscreen()}catch{}setPhase('test')};
 if(phase==='start')return <main><section className="card hero"><div className="tag">ERC ACADEMY • GRAMMAR ASSESSMENT</div><h1>Relative Clauses Test</h1><p>50 questions • 20 minutes • Score 0–100</p><input placeholder="Student full name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Class / group (optional)" value={group} onChange={e=>setGroup(e.target.value)}/><div className="warning"><b>Before you begin</b><br/>Once started, the timer cannot be paused. Leaving the tab, minimizing the browser, or exiting fullscreen will end and submit your attempt. Browser controls cannot guarantee prevention of operating-system screenshots.</div><button onClick={start}>Start test</button></section></main>;
 if(phase==='done')return <main><section className="card"><div className="tag">RESULTS & FEEDBACK</div><h1>{score}/100</h1><p><b>{name}</b>{group&&<> • {group}</>}</p><p>{questions.filter(q=>ans[q.id]===q.answer).length} correct of {questions.length} • {reason}</p><div className="result">{questions.map(q=><article key={q.id} className={ans[q.id]===q.answer?'ok':'bad'}><b>{q.id}. {q.text}</b><p>Your answer: {ans[q.id]||'No answer'}<br/>Correct answer: <strong>{q.answer}</strong><br/><small>{q.feedback}</small></p></article>)}</div><p className="evidence">Take a photo/screenshot of this results page and submit it to Google Classroom as instructed by your teacher.</p></section></main>;
 return <main><header><b>{name}</b><span>{Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</span></header><section className="card"><h1>Relative Clauses</h1><p className="muted">Answer every question. Your attempt is submitted automatically at 00:00.</p>{questions.map(q=><article className="q" key={q.id}><h3>{q.id}. {q.text}</h3>{q.options.map(o=><label key={o}><input type="radio" name={'q'+q.id} checked={ans[q.id]===o} onChange={()=>setAns({...ans,[q.id]:o})}/>{o}</label>)}</article>)}<button onClick={()=>confirm('Submit your test now?')&&submit()}>Submit test</button></section></main>
}createRoot(document.getElementById('root')!).render(<App/>);