export type Q={id:number,part:string,instruction:string,text:string,options:string[],answer:string,feedback:string};
const P:Record<number,[string,string]>={
1:['Part 1 — Defining vs. Non-defining Relative Clauses','Choose the best answer.'],
2:['Part 2 — Can You Drop the Relative Pronoun?','Choose DROP if the relative pronoun can be omitted. Choose KEEP if it cannot.'],
3:['Part 3 — Correct the Mistake','Each sentence contains one relative-clause mistake. Choose the correctly rewritten sentence.'],
4:['Part 4 — Prepositional Relative Clauses','Complete each sentence with the correct expression.'],
5:['Part 5 — Formal vs. Informal Prepositional Clauses','Choose the formal rewrite with the preposition before the relative pronoun.'],
6:['Part 6 — Nominal Relative Clauses','Choose the correct answer.'],
7:['Part 7 — Rewrite Using an -ever Word','Choose the rewrite that keeps the original meaning.'],
8:['Part 8 — Reduced Relative Clauses','Choose the correct reduced relative clause.'],
9:['Part 9 — Advanced Relative Phrases','Choose the best expression.']
};
const part=(id:number)=>id<=8?1:id<=14?2:id<=20?3:id<=26?4:id<=30?5:id<=36?6:id<=40?7:id<=46?8:9;
const make=(id:number,text:string,options:string[],answer:string,feedback:string):Q=>{const n=part(id);return{id,part:P[n][0],instruction:P[n][1],text,options,answer,feedback}};
export const questions:Q[]=[
make(1,'The developer ___ designed this application works for our company.',['which','who','whose','whom'],'who','Use who for a person functioning as the subject.'),
make(2,'My brother, ___ lives in Canada, is a software engineer.',['that','which','who','where'],'who','Non-defining clauses about people use who, not that.'),
make(3,'The laptop ___ I bought last month has already stopped working.',['who','whom','whose','which'],'which','Which can introduce a relative clause about a thing.'),
make(4,'Sarah, ___ project won the competition, has been promoted.',['who','whose','which','that'],'whose','Whose expresses possession.'),
make(5,'The office ___ we first met has been renovated.',['which','who','where','whose'],'where','Where refers to a place.'),
make(6,'The reason ___ the application crashed is still unclear.',['when','where','why','who'],'why','Why commonly follows reason.'),
make(7,'The conference, ___ was held in London, attracted over 5,000 people.',['that','which','where','what'],'which','Use which in a non-defining clause about a thing.'),
make(8,'2024 was the year ___ our company launched the platform.',['why','where','whose','when'],'when','When refers to a time.'),
make(9,'Can the pronoun be dropped? The programmer WHO developed the API has left.',['DROP','KEEP'],'KEEP','The pronoun is the subject of developed.'),
make(10,'Can the pronoun be dropped? The application THAT we tested yesterday contains bugs.',['DROP','KEEP'],'DROP','An object relative pronoun can be omitted in a defining clause.'),
make(11,'Can the pronoun be dropped? The customer WHOM I contacted this morning has not replied.',['DROP','KEEP'],'DROP','Whom is the object and may be omitted here.'),
make(12,'Can the pronoun be dropped? The server WHICH crashed last night is working again.',['DROP','KEEP'],'KEEP','Which is the subject of crashed.'),
make(13,'Can the pronoun be dropped? That is the problem THAT I told you about.',['DROP','KEEP'],'DROP','That is the object of the preposition at the end.'),
make(14,'Can the pronoun be dropped? My manager, WHO joined in 2018, is leaving.',['DROP','KEEP'],'KEEP','Relative pronouns are not dropped in non-defining clauses.'),
make(15,'Choose the correct sentence.',['The employee who I spoke to him yesterday was helpful.','The employee who I spoke to yesterday was helpful.','The employee which I spoke yesterday was helpful.'],'The employee who I spoke to yesterday was helpful.','Do not repeat the object with him.'),
make(16,'Choose the correct sentence.',['My manager, that lives in Miami, will attend.','My manager, who lives in Miami, will attend.','My manager who, lives in Miami will attend.'],'My manager, who lives in Miami, will attend.','Non-defining clauses about people use who.'),
make(17,'Choose the correct sentence.',['The software which it was released last week has bugs.','The software which was released last week has bugs.','The software who was released last week has bugs.'],'The software which was released last week has bugs.','Do not add it after the relative pronoun.'),
make(18,'Choose the correct formal sentence.',['That is the company to who I sent my application.','That is the company to whom I sent my application.','That is the company which whom I sent my application.'],'That is the company to whom I sent my application.','After a fronted preposition, use whom for people.'),
make(19,'Choose the correct sentence.',['The conference, that attracted thousands, lasted three days.','The conference, which attracted thousands, lasted three days.','The conference which, attracted thousands lasted three days.'],'The conference, which attracted thousands, lasted three days.','Use which, not that, in this non-defining clause.'),
make(20,'Choose the correct sentence.',['The woman which works in support solved it.','The woman who works in support solved it.','The woman whose works in support solved it.'],'The woman who works in support solved it.','Use who for a person as subject.'),
make(21,'The company employs 200 developers, many ___ work remotely.',['of which','of whom','in which','by whom'],'of whom','Quantifier + of whom refers to people.'),
make(22,'The system failed, ___ several orders were lost.',['as a result of which','of whom','at whom','by which time'],'as a result of which','This phrase expresses a consequence.'),
make(23,'We reached a stage ___ further testing became necessary.',['at which','of whom','whose','whenever'],'at which','At which point/stage identifies the point in a process.'),
make(24,'The company released ten applications, three ___ became successful.',['of which','of whom','at which','whose'],'of which','Quantifier + of which refers to things.'),
make(25,'The 1990s were a period ___ internet technology developed rapidly.',['in which','of whom','by whom','whatever'],'in which','Use in which for a period.'),
make(26,'The team was given a deadline ___ the project had to be completed.',['by which','of which','at whom','who'],'by which','By which expresses a deadline.'),
make(27,'Formal version: That is the developer who I was talking about.',['That is the developer about whom I was talking.','That is the developer about who I was talking.','That is the developer whom I was talking about him.'],'That is the developer about whom I was talking.','Formal English can place the preposition before whom.'),
make(28,'Formal version: This is the project which she is responsible for.',['This is the project for which she is responsible.','This is the project for that she is responsible.','This is the project which for she is responsible.'],'This is the project for which she is responsible.','Use preposition + which for things.'),
make(29,'Formal version: The client who we received the complaint from contacted us.',['The client from whom we received the complaint contacted us.','The client from who we received the complaint contacted us.','The client whom from we received contacted us.'],'The client from whom we received the complaint contacted us.','Use from whom in formal style.'),
make(30,'Formal version: This is the problem which we need to find a solution to.',['This is the problem to which we need to find a solution.','This is the problem to that we need a solution.','This is the problem whom we need a solution to.'],'This is the problem to which we need to find a solution.','A fronted preposition can precede which.'),
make(31,'You can choose ___ option works best for you.',['whatever','whoever','wherever','whenever'],'whatever','Whatever means any thing/option that fits.'),
make(32,'___ finishes the task first can leave early.',['Whatever','Wherever','Whoever','Whenever'],'Whoever','Whoever means any person who.'),
make(33,'You can work ___ you feel most productive.',['whoever','wherever','whichever','whatever'],'wherever','Wherever means any place where.'),
make(34,'Call me ___ you need help.',['whenever','whoever','whichever','wherever'],'whenever','Whenever means any time that.'),
make(35,'Take ___ laptop you prefer; there are three.',['whoever','whenever','whichever','wherever'],'whichever','Whichever selects freely from a limited set.'),
make(36,'I will support you ___ happens.',['whoever','wherever','whichever','whatever'],'whatever','Whatever happens = no matter what happens.'),
make(37,'It does not matter what you decide; I will support you.',['Whatever you decide, I will support you.','Whoever you decide, I will support you.','Wherever you decide, I will support you.'],'Whatever you decide, I will support you.','Whatever can mean no matter what.'),
make(38,'Anyone who wants to participate can join.',['Whoever wants to participate can join.','Whatever wants to participate can join.','Whenever wants to participate can join.'],'Whoever wants to participate can join.','Whoever replaces anyone who.'),
make(39,'You can contact me at any time you need assistance.',['You can contact me whenever you need assistance.','You can contact me wherever you need assistance.','You can contact me whoever you need assistance.'],'You can contact me whenever you need assistance.','Whenever expresses any time.'),
make(40,'You can sit in any seat you like.',['You can sit in whichever seat you like.','You can sit in whoever seat you like.','You can sit in whenever seat you like.'],'You can sit in whichever seat you like.','Whichever works with a choice among alternatives.'),
make(41,'Reduce: The man who is waiting outside is our new client.',['The man waiting outside is our new client.','The man waited outside is our new client.','The man who waiting outside is our new client.'],'The man waiting outside is our new client.','Active relative clauses can reduce to -ing participles.'),
make(42,'Reduce: Employees who work remotely must attend.',['Employees working remotely must attend.','Employees worked remotely must attend.','Employees who working remotely must attend.'],'Employees working remotely must attend.','Use the present participle for an active reduced clause.'),
make(43,'Reduce: The documents that were submitted yesterday are being reviewed.',['The documents submitted yesterday are being reviewed.','The documents submitting yesterday are being reviewed.','The documents were submitted yesterday being reviewed.'],'The documents submitted yesterday are being reviewed.','Passive relative clauses can reduce to a past participle.'),
make(44,'Reduce: Customers who are waiting for support should remain online.',['Customers waiting for support should remain online.','Customers waited for support should remain online.','Customers who waiting should remain online.'],'Customers waiting for support should remain online.','Remove who are and keep the -ing participle.'),
make(45,'Reduce: The products that are listed on this page are available.',['The products listed on this page are available.','The products listing on this page are available.','The products which listed are available.'],'The products listed on this page are available.','A passive clause reduces to the past participle.'),
make(46,'Reduce: Anyone who enters without authorization will be removed.',['Anyone entering without authorization will be removed.','Anyone entered without authorization will be removed.','Anyone who entering without authorization will be removed.'],'Anyone entering without authorization will be removed.','An active defining clause may reduce to -ing.'),
make(47,'We had almost completed the project, ___ the client changed the requirements.',['at which point','whose point','where point','which point'],'at which point','At which point links an event to a particular stage.'),
make(48,'The server went offline for six hours, ___ we could not process orders.',['in which case','during which time','no reason why','whose time'],'during which time','During which time refers to the six-hour period.'),
make(49,'He redesigned the database, ___ performance improved dramatically.',['as a result of which','the reason why','since when','whoever'],'as a result of which','This phrase connects a result to the preceding event.'),
make(50,'There is ___ the application should require access to your photos.',['the part where','no reason why','at which point','whichever'],'no reason why','No reason why is the appropriate relative phrase.')
];